name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, dom
      - name: Install dependencies
        run: composer install --no-interaction --no-progress
      - name: Run tests
        run: ./vendor/bin/phpunit --configuration tests/phpunit.xml
      - name: Package module
        run: zip -r module.zip app
      - name: Deploy to server
        if: github.ref == 'refs/heads/main'
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          TARGET_DIR: ${{ secrets.DEPLOY_PATH }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          scp -i deploy_key module.zip "$USER@$HOST:$TARGET_DIR/"
